package com.widgetforge.widget

// ════════════════════════════════════════════════════════════════
//  Auto-generated: 100 concrete AppWidgetProvider subclasses
//  4 types × 25 sizes (1×1 → 5×5)
//  All routing logic lives in BaseWidgetProvider.
//  The class name encodes the canonical grid size so the system
//  can present each size as a distinct entry in the widget picker.
// ════════════════════════════════════════════════════════════════

// ── TEXT ────────────────────────────────────────────────────────
class TextWidget1x1Provider : BaseWidgetProvider()
class TextWidget1x2Provider : BaseWidgetProvider()
class TextWidget1x3Provider : BaseWidgetProvider()
class TextWidget1x4Provider : BaseWidgetProvider()
class TextWidget1x5Provider : BaseWidgetProvider()
class TextWidget2x1Provider : BaseWidgetProvider()
class TextWidget2x2Provider : BaseWidgetProvider()
class TextWidget2x3Provider : BaseWidgetProvider()
class TextWidget2x4Provider : BaseWidgetProvider()
class TextWidget2x5Provider : BaseWidgetProvider()
class TextWidget3x1Provider : BaseWidgetProvider()
class TextWidget3x2Provider : BaseWidgetProvider()
class TextWidget3x3Provider : BaseWidgetProvider()
class TextWidget3x4Provider : BaseWidgetProvider()
class TextWidget3x5Provider : BaseWidgetProvider()
class TextWidget4x1Provider : BaseWidgetProvider()
class TextWidget4x2Provider : BaseWidgetProvider()
class TextWidget4x3Provider : BaseWidgetProvider()
class TextWidget4x4Provider : BaseWidgetProvider()
class TextWidget4x5Provider : BaseWidgetProvider()
class TextWidget5x1Provider : BaseWidgetProvider()
class TextWidget5x2Provider : BaseWidgetProvider()
class TextWidget5x3Provider : BaseWidgetProvider()
class TextWidget5x4Provider : BaseWidgetProvider()
class TextWidget5x5Provider : BaseWidgetProvider()

// ── IMAGE ───────────────────────────────────────────────────────
class ImageWidget1x1Provider : BaseWidgetProvider()
class ImageWidget1x2Provider : BaseWidgetProvider()
class ImageWidget1x3Provider : BaseWidgetProvider()
class ImageWidget1x4Provider : BaseWidgetProvider()
class ImageWidget1x5Provider : BaseWidgetProvider()
class ImageWidget2x1Provider : BaseWidgetProvider()
class ImageWidget2x2Provider : BaseWidgetProvider()
class ImageWidget2x3Provider : BaseWidgetProvider()
class ImageWidget2x4Provider : BaseWidgetProvider()
class ImageWidget2x5Provider : BaseWidgetProvider()
class ImageWidget3x1Provider : BaseWidgetProvider()
class ImageWidget3x2Provider : BaseWidgetProvider()
class ImageWidget3x3Provider : BaseWidgetProvider()
class ImageWidget3x4Provider : BaseWidgetProvider()
class ImageWidget3x5Provider : BaseWidgetProvider()
class ImageWidget4x1Provider : BaseWidgetProvider()
class ImageWidget4x2Provider : BaseWidgetProvider()
class ImageWidget4x3Provider : BaseWidgetProvider()
class ImageWidget4x4Provider : BaseWidgetProvider()
class ImageWidget4x5Provider : BaseWidgetProvider()
class ImageWidget5x1Provider : BaseWidgetProvider()
class ImageWidget5x2Provider : BaseWidgetProvider()
class ImageWidget5x3Provider : BaseWidgetProvider()
class ImageWidget5x4Provider : BaseWidgetProvider()
class ImageWidget5x5Provider : BaseWidgetProvider()

// ── GIF ─────────────────────────────────────────────────────────
class GifWidget1x1Provider : BaseWidgetProvider()
class GifWidget1x2Provider : BaseWidgetProvider()
class GifWidget1x3Provider : BaseWidgetProvider()
class GifWidget1x4Provider : BaseWidgetProvider()
class GifWidget1x5Provider : BaseWidgetProvider()
class GifWidget2x1Provider : BaseWidgetProvider()
class GifWidget2x2Provider : BaseWidgetProvider()
class GifWidget2x3Provider : BaseWidgetProvider()
class GifWidget2x4Provider : BaseWidgetProvider()
class GifWidget2x5Provider : BaseWidgetProvider()
class GifWidget3x1Provider : BaseWidgetProvider()
class GifWidget3x2Provider : BaseWidgetProvider()
class GifWidget3x3Provider : BaseWidgetProvider()
class GifWidget3x4Provider : BaseWidgetProvider()
class GifWidget3x5Provider : BaseWidgetProvider()
class GifWidget4x1Provider : BaseWidgetProvider()
class GifWidget4x2Provider : BaseWidgetProvider()
class GifWidget4x3Provider : BaseWidgetProvider()
class GifWidget4x4Provider : BaseWidgetProvider()
class GifWidget4x5Provider : BaseWidgetProvider()
class GifWidget5x1Provider : BaseWidgetProvider()
class GifWidget5x2Provider : BaseWidgetProvider()
class GifWidget5x3Provider : BaseWidgetProvider()
class GifWidget5x4Provider : BaseWidgetProvider()
class GifWidget5x5Provider : BaseWidgetProvider()

// ── CODE ────────────────────────────────────────────────────────
class CodeWidget1x1Provider : BaseWidgetProvider()
class CodeWidget1x2Provider : BaseWidgetProvider()
class CodeWidget1x3Provider : BaseWidgetProvider()
class CodeWidget1x4Provider : BaseWidgetProvider()
class CodeWidget1x5Provider : BaseWidgetProvider()
class CodeWidget2x1Provider : BaseWidgetProvider()
class CodeWidget2x2Provider : BaseWidgetProvider()
class CodeWidget2x3Provider : BaseWidgetProvider()
class CodeWidget2x4Provider : BaseWidgetProvider()
class CodeWidget2x5Provider : BaseWidgetProvider()
class CodeWidget3x1Provider : BaseWidgetProvider()
class CodeWidget3x2Provider : BaseWidgetProvider()
class CodeWidget3x3Provider : BaseWidgetProvider()
class CodeWidget3x4Provider : BaseWidgetProvider()
class CodeWidget3x5Provider : BaseWidgetProvider()
class CodeWidget4x1Provider : BaseWidgetProvider()
class CodeWidget4x2Provider : BaseWidgetProvider()
class CodeWidget4x3Provider : BaseWidgetProvider()
class CodeWidget4x4Provider : BaseWidgetProvider()
class CodeWidget4x5Provider : BaseWidgetProvider()
class CodeWidget5x1Provider : BaseWidgetProvider()
class CodeWidget5x2Provider : BaseWidgetProvider()
class CodeWidget5x3Provider : BaseWidgetProvider()
class CodeWidget5x4Provider : BaseWidgetProvider()
class CodeWidget5x5Provider : BaseWidgetProvider()
